/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.activemq.xbean;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.apache.activemq.broker.BrokerService;
import org.apache.activemq.util.IntrospectionSupport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * Loads a {@link BrokerService} from an XBean XML configuration file without
 * requiring a Spring ApplicationContext. Uses the XBean element-to-class
 * mapping generated by the maven-xbean-plugin together with DOM parsing and
 * reflection-based property injection.
 */
public class XBeanBrokerLoader {

    private static final Logger LOG = LoggerFactory.getLogger(XBeanBrokerLoader.class);

    /** Path where the maven-xbean-plugin stores element→class mappings. */
    private static final String MAPPING_RESOURCE =
            "META-INF/org.apache.xbean.spring.context.v2/mapping.properties";

    private final Map<String, String> elementToClass;
    /** Per-element metadata, e.g. "broker.init-method" → "afterPropertiesSet". */
    private final Map<String, String> elementMetadata;
    private final Map<String, Object> beanRegistry = new LinkedHashMap<>();

    public XBeanBrokerLoader() throws IOException {
        Map<String, String>[] maps = loadAllMappings();
        this.elementToClass = maps[0];
        this.elementMetadata = maps[1];
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Parse the XML at {@code configUrl} and return the {@link BrokerService}
     * it defines.
     */
    public BrokerService loadBroker(URL configUrl) throws Exception {
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(true);
        DocumentBuilder db = dbf.newDocumentBuilder();

        Document doc;
        try (InputStream is = configUrl.openStream()) {
            doc = db.parse(is);
        }

        Element root = doc.getDocumentElement();
        Object rootBean = processElement(root);

        String id = root.getAttribute("id");
        beanRegistry.put((id != null && !id.isEmpty()) ? id : "broker", rootBean);

        if (rootBean instanceof BrokerService) {
            return (BrokerService) rootBean;
        }

        // Fallback: search the registry
        for (Object bean : beanRegistry.values()) {
            if (bean instanceof BrokerService) {
                return (BrokerService) bean;
            }
        }

        throw new IllegalArgumentException(
                "No BrokerService found in config: " + configUrl);
    }

    /** Returns an unmodifiable view of all beans registered by id. */
    public Map<String, Object> getBeanRegistry() {
        return Collections.unmodifiableMap(beanRegistry);
    }

    // -------------------------------------------------------------------------
    // Mapping loading
    // -------------------------------------------------------------------------

    @SuppressWarnings("unchecked")
    private static Map<String, String>[] loadAllMappings() throws IOException {
        Map<String, String> classes = new LinkedHashMap<>();
        Map<String, String> metadata = new LinkedHashMap<>();
        ClassLoader cl = currentClassLoader();
        Enumeration<URL> urls = cl.getResources(MAPPING_RESOURCE);
        while (urls.hasMoreElements()) {
            Properties props = new Properties();
            try (InputStream is = urls.nextElement().openStream()) {
                props.load(is);
            }
            for (String key : props.stringPropertyNames()) {
                String value = props.getProperty(key).trim();
                if (key.indexOf('.') < 0) {
                    // Plain element name → class name
                    classes.put(key, value);
                } else {
                    // Metadata entry: "elementName.init-method", "elementName.destroy-method", etc.
                    metadata.put(key, value);
                }
            }
        }
        if (classes.isEmpty()) {
            LOG.warn("No XBean mapping found at {}; XML broker configuration may not work correctly.", MAPPING_RESOURCE);
        }
        return new Map[]{classes, metadata};
    }

    // -------------------------------------------------------------------------
    // XML processing
    // -------------------------------------------------------------------------

    private Object processElement(Element element) throws Exception {
        String localName = localName(element);
        String className = elementToClass.get(localName);

        if (className == null) {
            LOG.debug("No XBean class mapping for element <{}>; skipping.", localName);
            return null;
        }

        Class<?> clazz = loadClass(className);
        Object bean = clazz.getDeclaredConstructor().newInstance();

        applyAttributes(bean, element);
        applyChildren(bean, element);

        String id = element.getAttribute("id");
        if (id != null && !id.isEmpty()) {
            beanRegistry.put(id, bean);
        }

        callInit(bean, localName);
        return bean;
    }

    /** Set XML attributes as bean properties (excluding xmlns / id). */
    private void applyAttributes(Object bean, Element element) {
        Map<String, String> props = new HashMap<>();
        NamedNodeMap attrs = element.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++) {
            Node a = attrs.item(i);
            String name = a.getLocalName();
            if (name == null) name = a.getNodeName();
            if (name.equals("id") || name.startsWith("xmlns") || name.contains(":")) {
                continue;
            }
            props.put(name, a.getNodeValue());
        }
        if (!props.isEmpty()) {
            try {
                IntrospectionSupport.setProperties(bean, props);
            } catch (Exception e) {
                LOG.debug("Could not apply attributes to {}: {}", bean.getClass().getSimpleName(), e.getMessage());
            }
        }
    }

    /** Recursively process child elements and inject them into the parent bean. */
    private void applyChildren(Object parent, Element element) throws Exception {
        // Group child elements by local name
        Map<String, List<Element>> groups = new LinkedHashMap<>();
        NodeList children = element.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);
            if (child instanceof Element) {
                String name = localName((Element) child);
                groups.computeIfAbsent(name, k -> new ArrayList<>()).add((Element) child);
            }
        }

        for (Map.Entry<String, List<Element>> entry : groups.entrySet()) {
            String childName = entry.getKey();
            List<Element> childElements = entry.getValue();
            String childClass = elementToClass.get(childName);

            if (childClass == null) {
                // Wrapper element with no own class: treat its content as property children
                for (Element wrapper : childElements) {
                    applyChildren(parent, wrapper);
                }
                continue;
            }

            if (childElements.size() == 1) {
                Object child = processElement(childElements.get(0));
                if (child != null) {
                    setChildOnParent(parent, childName, child);
                }
            } else {
                List<Object> list = new ArrayList<>();
                for (Element el : childElements) {
                    Object child = processElement(el);
                    if (child != null) list.add(child);
                }
                setChildOnParent(parent, childName, list);
            }
        }
    }

    /**
     * Try to set {@code value} on {@code parent} using a property named
     * {@code childName}. Falls back to the pluralised name for list values.
     */
    private void setChildOnParent(Object parent, String childName, Object value) {
        // Try exact name first
        if (IntrospectionSupport.setProperty(parent, childName, value)) {
            return;
        }
        // Try pluralised name (e.g. "transportConnector" → "transportConnectors")
        if (IntrospectionSupport.setProperty(parent, childName + "s", value)) {
            return;
        }
        LOG.debug("Could not set property '{}' on {}", childName, parent.getClass().getSimpleName());
    }

    /**
     * Calls the init method on a freshly configured bean. Checks, in order:
     * <ol>
     *   <li>The XBean mapping metadata entry {@code elementName.init-method}</li>
     *   <li>The conventional {@code afterPropertiesSet()} method</li>
     * </ol>
     */
    private void callInit(Object bean, String elementName) {
        // 1. Explicit init-method from XBean mapping metadata
        String initMethod = elementMetadata.get(elementName + ".init-method");
        if (initMethod != null && !initMethod.isEmpty()) {
            try {
                bean.getClass().getMethod(initMethod).invoke(bean);
                return;
            } catch (NoSuchMethodException ignored) {
                // mapping may be stale; fall through
            } catch (Exception e) {
                LOG.warn("Init method '{}' failed on {}: {}", initMethod,
                        bean.getClass().getSimpleName(), e.getMessage());
            }
        }

        // 2. XBean / Spring convention: afterPropertiesSet()
        try {
            bean.getClass().getMethod("afterPropertiesSet").invoke(bean);
        } catch (NoSuchMethodException ignored) {
            // bean has no init method
        } catch (Exception e) {
            LOG.warn("afterPropertiesSet() failed on {}: {}", bean.getClass().getSimpleName(), e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static String localName(Element element) {
        String name = element.getLocalName();
        return (name != null) ? name : element.getTagName();
    }

    private static Class<?> loadClass(String className) throws ClassNotFoundException {
        return currentClassLoader().loadClass(className);
    }

    private static ClassLoader currentClassLoader() {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        return (cl != null) ? cl : XBeanBrokerLoader.class.getClassLoader();
    }
}
